version: 1

snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo 
      - osusergo
    ldflags:
      - -s
      - -w
      - -X "rancherlabs/cattle-drive/pkg/version.GitCommit={{ .FullCommit }}"
      - -X "rancherlabs/cattle-drive/pkg/version.Version=v{{ .Version }}"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: rancherlabs
    name: cattle-drive
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
